<?php
const STORAGE_PATH ='storage' . DIRECTORY_SEPARATOR;
const PAGES_PATH = 'app' . DIRECTORY_SEPARATOR . 'views' . DIRECTORY_SEPARATOR . 'pages' . DIRECTORY_SEPARATOR;
const CLASSES_PATH = 'app' . DIRECTORY_SEPARATOR . 'classes' . DIRECTORY_SEPARATOR;
const CORE_PATH = 'app' . DIRECTORY_SEPARATOR . 'core' . DIRECTORY_SEPARATOR;
const CONTROLLER_PATH = 'app' . DIRECTORY_SEPARATOR . 'controllers' . DIRECTORY_SEPARATOR;
const MODEL_PATH = 'app' . DIRECTORY_SEPARATOR . 'models' . DIRECTORY_SEPARATOR;

const CLASS_PATHS = [
    CLASSES_PATH,
    CORE_PATH,
    CONTROLLER_PATH,
    MODEL_PATH,
];